### ISSUE TITLE
use rustup rls

### ISSUE THREAD

**Issue by m4b** [emacs-lsp/lsp-rust#1]
the rust language server is now available via rustup: http://www.jonathanturner.org/2017/04/rls-now-in-nightly.md.html

What this means is the check for `RLS_ROOT` shouldn't be necessary (unless compiling from source); I propose to make this default method to invoke `rls` (e.g., just `rls` as it should be in the users path), and if not found, require `RLS_ROOT` (perhaps they're testing the latest compiled version)

**Comment by vibhavp** [comment]
Done, thanks.
