### ISSUE TITLE
No definitions found for: lsp-provide-marked-string-renderer

### ISSUE THREAD

**Issue by rattit0** [emacs-lsp/lsp-rust#15]
https://github.com/emacs-lsp/lsp-rust/blob/a281f3daa4953be8f1ae2c35d3fb9059ae58ef0c/lsp-rust.el#L82

**Comment by vibhavp** [comment]
Oops, forgot to push the corresponding update to lsp-mode. Done: https://github.com/emacs-lsp/lsp-mode/commit/0e1d308d8635bfad4f4f4b7c49c76eb2a3d61fad
