### ISSUE TITLE
"Unknown method" error messages

### ISSUE THREAD

**Issue by brotzeit** [emacs-lsp/lsp-rust#19]
I have problems configuring lsp.

``` elisp
(require 'lsp-mode)
(require 'lsp-rust)
(setq lsp-rust-rls-command '("rustup" "run" "nightly" "rls"))

(add-hook 'rust-mode-hook #'lsp-rust-enable)
(add-hook 'rust-mode-hook #'lsp-mode)

(lsp-define-stdio-client rust-mode 
                         "rust"
                         #'lsp-rust--get-root
                         lsp-rust-rls-command)

(add-hook 'rust-mode-hook #'rust-mode-enable)
```

When I open a rust file the rls process starts but I get these error messages

```
Unknown method: rustDocument/beginBuild
Unknown method: rustDocument/diagnosticsBegin
Unknown method: rustDocument/diagnosticsEnd
```

**Comment by sebastiencs** [comment]
You don't need to redefine the client. It's already done in lsp-rust.el
You can delete those lines:
```elisp

(add-hook 'rust-mode-hook #'lsp-rust-enable)
(add-hook 'rust-mode-hook #'lsp-mode)

(lsp-define-stdio-client rust-mode 
                         "rust"
                         #'lsp-rust--get-root
                         lsp-rust-rls-command)
```

**Comment by brotzeit** [comment]
Thanks for the fast answer. But when I remove the hooks, the process doesn't start and lsp-mode isn't enabled. I also couldn't find the hooks in lsp-rust.el, except in the commentary part.

**Comment by sebastiencs** [comment]
Sorry I misread your code. 
This should be good:
```elisp
(require 'lsp-mode)
(require 'lsp-rust)
(setq lsp-rust-rls-command '("rustup" "run" "nightly" "rls"))
(add-hook 'rust-mode-hook #'lsp-rust-enable)
```

**Comment by brotzeit** [comment]
The process is running, but I can't find definitions or references with `xref`.

**Comment by sebastiencs** [comment]
Does `xref` returns any error ?
Is there an error in the buffer `lsp-rust stderr`

**Comment by brotzeit** [comment]
Sorry I didn't answer. I thought maybe the rls stuff is more mature in a few months and it will work without further investigation. It seems I was right ;D

Thanks for your work. This is really nice!
