### ISSUE TITLE
Questions : does lsp-rust work in single file?

### ISSUE THREAD

**Issue by samrayleung** [emacs-lsp/lsp-rust#25]
It seems `lsp-rust` only works in a project, I could not make it work in single file. For example if I create a rust file in `tmp`, `lsp-rust` will complain:
```
File mode specification error: (error Couldn’t find root for project at /tmp/)
```
or I haven't configured it in a right way ?

**Comment by vibhavp** [comment]
I dont think so. RLS requires a project to use cargo.

**Comment by samrayleung** [comment]
well, get it. I just think it is a little bit tremendous/clumsy. As for the cargo command, I think I could use [cargo-script](https://github.com/DanielKeep/cargo-script)
