### ISSUE TITLE
No Language server associated with this buffer/Installation help

### ISSUE THREAD

**Issue by malynome** [emacs-lsp/lsp-rust#29]
Hi, sorry for cluttering the issues, but I didn't know where to ask for help. I'm trying to install lsp-rust, to test it out. I have followed the steps, but when I run lsp-capabilities, no server is found. Clearly I'm doing something wrong, but I'm new to Emacs, and configuring this whole thing is somewhat of an undertaking. I'm also running spacemacs, could this be causing any conflicts? I'm on Linux, have the RLS set up, and it can be run from the commandline.
Thanks in advance.

**Comment by happycoder97** [comment]
I have this problem too.
I added this to `~/.emacs`.
```elisp
(with-eval-after-load 'lsp-mode                                                                         
(setq lsp-rust-rls-command '("rustup" "run" "nightly" "rls"))                                         
(require 'lsp-rust))                                                                                  
(add-hook 'rust-mode-hook #'lsp-rust-enable)                                                            
(add-hook 'rust-mode-hook #'flycheck-mode)                                                              
```
Then when I open a rust project, I did `M-x lsp-mode` `M-x lsp-rust-enable`,
and when I run `M-x lsp-capabilities`, it says:
```
No language server is associated with this buffer                                                            
```
I am running vanilla Emacs v26.1

**Comment by miladz68** [comment]
I am having the same issue. may be better instructions are needed. I am using use-package but I cannot rust rls no matter what I do.

**Comment by happycoder97** [comment]
@miladz68 Switch to vscode. Saved me from a lot of headaches :)
