### ISSUE TITLE
Error loading autoloads: (void-function lsp-define-stdio-client)

### ISSUE THREAD

**Issue by Dushistov** [emacs-lsp/lsp-rust#6]
Steps to reproduce:

run emacs 25 with such `~/.emacs`:
```elisp
(package-initialize)

(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
```

install `lsp-rust` with `M-x list-packages`,
restart emacs and see this message (bug topic I mean).

the source of problem is `lsp-rust-autoloads.el` that not contains `(require 'lsp-mode)` and
`(require 'lsp-rust)`, but execute functions from both of them via

```elisp
(lsp-define-stdio-client 'rust-mode "rust" 'stdio
                   #'lsp-rust--get-root
                    "Rust Language Server"
                   (lsp-rust--rls-command))
```

**Comment by vibhavp** [comment]
Remove the `;;;autoload` from lsp-rust.el should fix this, could you try that?

On Sun, Jul 23, 2017 at 6:06 AM, Evgeniy Dushistov
<notifications@github.com> wrote:
> Steps to reproduce:
>
> run emacs 25 with such ~/.emacs:
>
> (package-initialize)
>
> (require 'package)
> (add-to-list 'package-archives
>              '("melpa" . "https://melpa.org/packages/"))
>
> install lsp-rust with M-x list-packages,
> restart emacs and see this message.
>
> the source of problem is lsp-rust-autoloads.el that not contains (require
> 'lsp-mode) and
> (require 'lsp-rust), but execute functions from both of them via
>
> (lsp-define-stdio-client 'rust-mode "rust" 'stdio
>                    #'lsp-rust--get-root
>                     "Rust Language Server"
>                    (lsp-rust--rls-command))
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Vibhav Pant
vibhavp@gmail.com

**Comment by Dushistov** [comment]
@vibhavp 

>Remove the `;;;autoload` from lsp-rust.el should fix this, could you try that?

I don't think that helps me with my setup,
I get `lsp` stuff from melpa, so `lsp-rust-autoloads.el` already generated,
so if I remove `;;;autoload` nothing changed.

Instead of I edited `lsp-rust-autoloads.el` and add suitable `require` before `lsp-define-stdio-client` call.

But this workaround works untill new update in `lsp-rust`, so I report this issue.

In fact, in theory  this feature is nice thing to have - install `lsp-rust` and that's all,
nothing to configure.

**Comment by vibhavp** [comment]
I'll remove the autoloads for now, then
