### ISSUE TITLE
Silence RLS client errors

### ISSUE THREAD

**Issue by MageSlayer** [emacs-lsp/lsp-rust#9]
Hi

Recent lsp-rust + Rust nightly produce error messages every time.
Following expression seems to silence them. Please commit or comment :)

```
(lsp-client-on-notification 'rust-mode "rustDocument/beginBuild"
			    #'(lambda (_w _p)))
(lsp-client-on-notification 'rust-mode "client/registerCapability"
			    #'(lambda (_w _p)))
(lsp-client-on-notification 'rust-mode "client/unregisterCapability"
			    #'(lambda (_w _p)))
```

**Comment by vibhavp** [comment]
`{un}registerCapability` is actually a method as opposed to a server side notification. Once https://github.com/emacs-lsp/lsp-mode/pull/131 is merged, I'll push a fix for this.
